name: Dockerfile lint

on:
  push:
    branches: main
  pull_request:
    branches: main
    paths:
      - 'Dockerfile'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker lint
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning
