name: Go lint, build, and test

on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  lint:
    runs-on: ubuntu-latest
    container: ghcr.io/opencontainers/golangci-lint:v1.39.0
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: make lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.7
      - name: Build
        run: make build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.7
      - name: Formatting
        run: if [ -n "$(go fmt)" ]; then echo 'Code is not formatted with "go fmt"'; false; fi
      - name: Test
        run: make test
