name: Go lint, build, and test

on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.1
      - name: Lint
        uses: docker://golangci/golangci-lint:v1.42
        run: make lint
      - name: Build
        run: make build
      - name: Formatting
        run: if [ -n "$(go fmt)" ]; then echo 'Code is not formatted with "go fmt"'; false; fi
      - name: Test
        run: make test
