name: Go lint, build, and test

on:
  push:
    branches: ${{ github.event.repository.default_branch }}
  pull_request:
    branches: ${{ github.event.repository.default_branch }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Lint
        run: make lint
      - name: Build
        run: make build
      - name: Formatting
        run: if [ -n "$(go fmt)" ]; then echo 'Code is not formatted with "go fmt"'; false; fi
      - name: Test
        run: make test
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.0.9
        with:
          args: --verbose --no-progress --offline docs/src/*.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
