name: Dockerfile lint and markdown test

on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.0.9
        with:
          args: --verbose --no-progress --offline docs/src/*.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Vale
        uses: errata-ai/vale-action@v1.4.0
        with:
          styles: https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
          config: https://raw.githubusercontent.com/errata-ai/vale/master/.vale.ini
          files: docs/src
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
